# Generated by Django 5.0.6 on 2024-05-12 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.CharField(max_length=10)),
                ('marca', models.CharField(max_length=20)),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.PositiveBigIntegerField()),
                ('fecha', models.DateField()),
            ],
        ),
    ]
